### ISSUE TITLE
Angular 9.1.X warnings

### ISSUE THREAD

**Issue by phcaridade** [efgiese/ngx-barcode6#10]
Hi,
I'm having these two warnings with Angular 9.1.7:
`WARN ngx-barcode6@1.0.10 requires a peer of @angular/common@>=6.0.0 < 9.0.0 but none is installed`
`WARN ngx-barcode6@1.0.10 requires a peer of @angular/core@>=6.0.0 < 9.0.0 but none is installed.`

Is this something that could be addressed in a future (hope soon) version?
Thank you for your attention.

**Comment by efgiese** [comment]
Please try the new version
