### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by igorosabel** [efgiese/ngx-barcode6#12]
Hi!
Yesterday Angular 10 was released and when I tried to update this error messages showed up:

`Package "ngx-barcode6" has an incompatible peer dependency to "@angular/core" (requires ">=6.0.0 < 9.0.0" (extended), would install "10.0.0").`

Could you please update to add Angular 10 support?

Thanks!

**Comment by TheParad0X** [comment]
Same here. Please add Angular 10 support.

**Comment by efgiese** [comment]
Please try the new version
