### ISSUE TITLE
getInternalNameOfClass() called on a non-ES5 class

### ISSUE THREAD

**Issue by ThomasLebrun** [efgiese/ngx-barcode6#14]
I'm trying to build an Angular 9 app with the latest version (1.0.12) and I'm getting the following error:

![image](https://user-images.githubusercontent.com/4185315/87661494-fe922580-c760-11ea-8bae-6a99d2773ab6.png)

Any ideas ?

Thanks !

**Comment by efgiese** [comment]
Is it a new fresh install project? I have test it on a fresh install new project like in the readme and i am getting no error.
Perhaps you have to clean the cache or delete the node_modules directory and run npm install...

**Comment by efgiese** [comment]
No answer?!
