### ISSUE TITLE
Angular 10.1.0 support

### ISSUE THREAD

**Issue by igorosabel** [efgiese/ngx-barcode6#15]
Hi! Angular released this week the 10.1.0 version and when I try to update I get this error:

```
Package "ngx-barcode6" has an incompatible peer dependency to "@angular/common" (requires ">=6.0.0 <10.1.0" (extended), would install "10.1.0").
Package "ngx-barcode6" has an incompatible peer dependency to "@angular/core" (requires ">=6.0.0 <10.1.0" (extended), would install "10.1.0").
```

My project uses these right now and I'm proposed to update to these other versions:

```
@angular/cdk  10.1.3 -> 10.2.0
@angular/cli  10.0.8 -> 10.1.0
@angular/core  10.0.14 -> 10.1.0
@angular/material  10.1.3 -> 10.2.0

```
Thanks

**Comment by TheParad0X** [comment]
Same Problem here.

**Comment by TheParad0X** [comment]
As a workaround, I removed "ngx-barcode6": "^1.0.12" from my package.json, I migrated to the latest Angular 10, and then I added it again.

**Comment by igorosabel** [comment]
Could work, but Angular guys deliver updates weekly, and I don't think it's a good practice to do that "trick" every week 🤣

Thanks by the way

**Comment by efgiese** [comment]
I have updated the lib. Please give it another try...

**Comment by igorosabel** [comment]
Works perfectly :D

Thanks!!
