### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by danielberebel** [efgiese/ngx-barcode6#17]
I'm need to render barcodes on angular 11 app, do you think you could update the dependencies? Thanks

**Comment by efgiese** [comment]
Now it is updated, please give it a try

**Comment by danielberebel** [comment]
On package file angular is locked to v10

**Comment by efgiese** [comment]
Please remove the package and add it once more. It is not locked to v10.

**Comment by danielberebel** [comment]
Thanks, now I can see the new commit and package works fine
