### ISSUE TITLE
Optimization bailouts

### ISSUE THREAD

**Issue by projectX21** [efgiese/ngx-barcode6#22]
I get the following warning:
```
Warning: .../app.module.ts depends on 'ngx-barcode6'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Are there really any optimization bailouts?

**Comment by ahmadfaizan** [comment]
I have the same issue, except I get errors and I can't run the application. Can someone please provide an insight why this might be happening

**Comment by efgiese** [comment]
Please remove the "node_modules" directory, the package-lock.json file and do the "npm install" once more. 
What errors do you get?
