### ISSUE TITLE
Missing barcode type "ITF"

### ISSUE THREAD

**Issue by LouisXhaferi** [efgiese/ngx-barcode6#23]
While supported in the original JsBarcode, your wrapper seems to be missing the definition of the barcode type of "ITF" without a fixed length requirement.

[Link to lindell/JsBarcode and it's folder structure](https://github.com/lindell/JsBarcode/tree/master/src/barcodes/ITF)

Definition in this library in _projects/ngx-barcode6/src/lib/ngx-barcode6.component.ts_
```js
@Input('bc-format') format: '' | 'CODE128' | 'CODE128A' | 'CODE128B' | 'CODE128C' | 'EAN13' | 'UPC' | 'EAN8' | 'EAN5' |
    'EAN2' | 'CODE39' | 'ITF14' | 'MSI' | 'MSI10' | 'MSI11' | 'MSI1010' | 'MSI1110' | 'pharmacode' | 'codabar' = 'CODE128';
```

Just adding it to the union would probably fix this. :)

**Comment by efgiese** [comment]
The new version is online...
