### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by berhir** [efgiese/ngx-barcode6#25]
Do you have plans to update to Angular 13?

**Comment by efgiese** [comment]
I'm working on it...

There are some breaking changes with Angular 13 because of 'strict' and 'ivy'.

**Comment by berhir** [comment]
Hi @efgiese, any news about the progress?

**Comment by chirichok98** [comment]
Hi @efgiese, can you take a look at #27  ?

**Comment by efgiese** [comment]
See new release...
