### ISSUE TITLE
Some barcodes aren't shown

### ISSUE THREAD

**Issue by JavierT** [efgiese/ngx-barcode6#26]
Hi, 
I have noticed than in an Angular 12 (12.2.12 is what I use), some barcodes like pharmacode, codabar, EAN and Code128A, Code128C, UPC (between others)  aren't working. It doesn't matter the bc-elemet-type we use. I have the same issue in the demo.

There is no error, just an empty <svg> or <img>

Thank you and great work.

**Comment by efgiese** [comment]
Hi,
sorry i can not reproduce that problem. I have installed the Angular 12.2.12 cli and started with a brand new project. I have installed the ngx-barcode6 and jsbarcode module and added the demo code (see README.md).

Please remove the "node_module" directory and the package-lock.json. Then do the npm install once more.

Please keep in mind that for some barcodes some values are not allowed.
