### ISSUE TITLE
EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Josebr1** [efgiese/ngx-barcode6#32]
Hi

I'm working on an **Angular 6** project and when starting the application with the `ng serve` command I came across this error

Environment:
Node via nvm - 8.17 - 16LTS e 17

npm 8.1.0

```
Error: ./node_modules/ngx-barcode6/fesm2015/ngx-barcode6.mjs 333:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
```

**Comment by efgiese** [comment]
Please use an older version of ngx-barcode6. Perhaps version 1.0.9

**Comment by bryananthonylewis** [comment]
> Please use an older version of ngx-barcode6. Perhaps version 1.0.9

This worked for me.

**Comment by efgiese** [comment]
Thank you...
