### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by igorosabel** [efgiese/ngx-barcode6#34]
Yesterday Angular 14 was released, I have a project where I use ngx-barcode 6 and when I tried to upgrade it I got this error:

⠴ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ngx-barcode6@1.0.20
npm ERR! Found: @angular/common@14.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.0.0
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^14.0.0" from the root project
npm ERR!     peer @angular/cdk@"14.0.0" from @angular/material@14.0.0
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^14.0.0" from the root project
npm ERR!     1 more (@swimlane/ngx-charts)
npm ERR!   6 more (@angular/forms, @angular/material, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=9.0.0 <14.0.0" from ngx-barcode6@1.0.20
npm ERR! node_modules/ngx-barcode6
npm ERR!   ngx-barcode6@"^1.0.20" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@">=9.0.0 <14.0.0" from ngx-barcode6@1.0.20
npm ERR!   node_modules/ngx-barcode6
npm ERR!     ngx-barcode6@"^1.0.20" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\igorosabel\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\igorosabel\AppData\Local\npm-cache\_logs\2022-06-03T08_07_22_528Z-debug-0.log
✖ Package install failed, see above.
× Migration failed. See above for further details.

Thanks!

**Comment by romarioputra** [comment]
For now just --force it and see if there any conflicted support

**Comment by igorosabel** [comment]
Hi, works but...

The ng update process does several things:

- updates the package.json
- does a npm install
- runs several migrations to update possible breaking changes

The npm install part fails because of the dependencies, but since the package.json was updates I could run `npm install --force` and force it to install everything.
But the migrations didn't end because they were interrupted. I've tried to copy the changes done in another project but I can't be sure if I left anything out...

So, yes, using --force worked (and I see it working) but I can't put this on production because there might be something else that can fail and I haven't found yet.

Thanks anyway :)

**Comment by projectX21** [comment]
+1

**Comment by TuroczyX** [comment]
+1

**Comment by rohanahata** [comment]
+1

**Comment by radawson** [comment]
+1

**Comment by efgiese** [comment]
Support Angular 14 is out...
