### ISSUE TITLE
Could you update the compatibility with Angular 8?

### ISSUE THREAD

**Issue by ingeJulianLasso** [efgiese/ngx-barcode6#4]
Your library is great and I use it daily in my personal developments, it is possible to update the library to be compatible with Angular 8 and thus be able to update the projects please.

**Comment by efgiese** [comment]
I think it works with Angular 8.
Can you submit any error message?

**Comment by csidro** [comment]
Hi, the package has a peer dependency of @angular/core and @angular/common.
Min version is 6.0.0, max version is 8.0.0. So it would work with Angular 8.0, but I can't update to Angular 8.1.3.
Could you please update the package to enable Angular 8.1 also?

**Comment by efgiese** [comment]
Hi,
now give it a try....
