### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by rostamiani** [efgiese/ngx-barcode6#7]
I just upgraded my Angular project to version 9 and this package has some problems with Ivy.
This is the error message:

`ERROR in ./node_modules/ngx-barcode6/__ivy_ngcc__/fesm2015/ngx-barcode6.js
Module not found: Error: Can't resolve 'jsbarcode' in 'D:\Projects\Nafis Global System\UI\node_modules\ngx-barcode6\__ivy_ngcc__\fesm2015'`

How can I fix this?

**Comment by efgiese** [comment]
How did you install the package? Did you install it like in the readme?
npm install --save ngx-barcode6 jsbarcode@3.11.0

**Comment by rostamiani** [comment]
Thanks
This fixed the problem
I was missing jsbarcode
But the weird thing is that this app was working in the Angular 8 version!

**Comment by DanielFrugoni-dev** [comment]
Any barcode that work with angular 9 and >9 ?, I see only old versions !

**Comment by efgiese** [comment]
Please try the new version
